---
- hosts: dev
  sudo: True
  vars:
    update_apt_cache: false
    server_name: "52.5.45.80"
    web_server_name: "dev.powerli.ne 52.5.45.80/web"
    cert_path: targets/dev/certs
    cert_file: apns-dev-civix.pem
    parameters_file: targets/dev/config/parameters.yml
    config_js_file: targets/dev/config/config.js
  roles:
    - setup
    - configure
    - monitoring
    - deploy

  pre_tasks:
      - name: update apt if needed
        apt: update_cache=yes
        when: update_apt_cache
