---
- hosts: vagrant
  vars:
    update_apt_cache: false
    server_name: admin.vagrant.local api.vagrant.local
  roles:
    - setup-vagrant

  pre_tasks:
      - name: update apt if needed
        apt: update_cache=yes
        when: update_apt_cache
